---
name: terraform-aws-vpc-peering
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    paths-ignore:
      - '**.md'

jobs:
  terraform-static:
    name: terraform-fmt
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform: ['1.5.7', '1.7.3']
    steps:
      -  uses: actions/checkout@master
      -  uses: hashicorp/setup-terraform@v1
         with:
           terraform_version: ${{ matrix.terraform }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

  terratest:
    name: terratest
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        terraform: ['1.5.7', '1.7.3']
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          go-version-file: tests/go.mod
          cache-dependency-path: tests/go.sum

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Build Dependencies
        env:
          TF_VERSION: ${{ matrix.terraform }}
        run: >
          wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip -O /tmp/terraform.zip &&
          sudo unzip -d /tmp/ /tmp/terraform.zip &&
          sudo mv /tmp/terraform /usr/local/bin/ 

      - name: Start Localstack
        run: docker compose up -d

      - name: Terratest
        run: |
          cd test
          go test -v -timeout=30m test/...
